spring:
  h2:
    console:
      enabled: true
  datasource:
    #url: jdbc:h2:mem:test;MODE=MySQL
    #url: jdbc:h2:~/test
    #url: jdbc:h2:~/temp/test
    username: sa
    password:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://127.0.0.1/~/temp/test
  jpa:
    hibernate:
      ddl-auto: create


