server:
  port: 8080
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

  datasource:
    url:  jdbc:h2:tcp://localhost/~/project
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    properties:
      hibernate:
    hibernate:
      ddl-auto: create


#jdbc:h2:tcp://127.0.0.1/~/project
##jdbc:h2:/~/project

